FROM nginx:1.19.7
RUN rm /etc/nginx/conf.d/default.conf && \
cat <<EOF > /etc/nginx/conf.d/server.conf && service nginx restart
http   {

upstream server_group   {

server your-svc.blue.svc.cluster.local weight=4;

server your-svc.green.svc.cluster.local weight=1;

}
server {
  listen 80;
  location / {
    proxy_pass "http:server_group";
    proxy_buffering off;
}
}
EOF
